### ISSUE TITLE
package undefined does not exist import undefined.CustomerIOReactNativePackage;

### ISSUE THREAD

**Issue by Birat77** [customerio/customerio-reactnative#323]
**SDK version:** 3.9.0

**Environment:** Development
React Native version 0.68.5

**Describe the bug**

When building the project after upgrading the package from v2 to v3, I keep getting this error.

```
demoapp/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:41: error: package undefined does not exist
import undefined.CustomerIOReactNativePackage;
                ^
demoapp/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:162: error: cannot find symbol
      new CustomerIOReactNativePackage(),
          ^
  symbol:   class CustomerIOReactNativePackage
  location: class PackageList
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
**To Reproduce**

Migrating from v2 to v3.9

**Expected behavior**

**Screenshots**

**Additional context**

To debug, I have already added these on MainApplication.java file but I keep getting the above error of undefined import in generated PackageList file.

import io.customer.reactnative.sdk.CustomerIOReactNativePackage; // Add this import ---

```
        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();

          packages.add(new RNAppsFlyerPackage());
          packages.add(new CustomerIOReactNativePackage()); // Add this to the list ----
          return packages;
        }
```

**Comment by mrehan27** [comment]
Hi @Birat77. Thanks for reaching out and sharing the details. Sorry to hear about the challenges you're facing while upgrading. To help you better, could you please answer the following questions:

- Can you confirm if you've followed all the steps mentioned in [the migration guide](https://www.customer.io/docs/sdk/react-native/updates-and-troubleshooting/migrate-upgrade/#upgrade-from-2x-to-3x)?
- Are there any additional steps or details that you followed and think could be helpful for us to identify the root cause?
- You shouldn't need to add `CustomerIOReactNativePackage` to your `MainApplication` as auto-linking should add for you. Can you try cleaning the project, removing `node_modules` folder, reinstalling dependencies, and then running the app to see if that fixes the problem for you?
- Since you mentioned you're currently running the app on `0.68.5`, which is quite an old version. Can you please try upgrading your React Native version to a newer one? Gradle support may be limited with such old versions. Our SDK now supports Gradle 8, which requires at least Gradle version `7.4.1` to work and may not function correctly with older versions.

The steps shared above should help troubleshoot the issue. Let us know if you have any more questions!

**Comment by birat-pandey** [comment]
All the steps were followed from the migration guide.
There are lots of packages to upgrade for the react-native. 
Currently I'm using gradle version 7.6.
I will try upgrading the react-native app to >0.70 and try again

**Comment by mrehan27** [comment]
Closing due to inactivity. Please feel free to reopen if needed or ask any further questions you may have.
